source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!

target 'JustPersist_Example' do
    
  pod 'JustPersist/Skopelos', :path => '../'
  pod 'JustPersist/MagicalRecord', :path => '../'
  
  target 'JustPersist_watchOS_Example Extension' do
      platform :watchos, '3.0'
      inherit! :search_paths
      
  end
  
  target 'JustPersist_Tests' do
      inherit! :search_paths
      
  end
end


post_install do |installer|

  installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
        configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
  
  installer.pods_project.targets.each do |target|
    puts target.name
  end
  
end
